### ISSUE TITLE
Strain rate partitioning

### ISSUE THREAD

**Issue by ArneSpang** [JuliaGeodynamics/GeoParams.jl#71]
Hi everyone,
compute_τij looks very useful. Is it possible to also make it return the strain rate of the individual rheological components? This would be important for shear heating and/or grain size reduction. Alternatively, returning effective viscosities of the individual components would also work. I had a look but at this point, I cannot follow the source code anymore.

**Comment by albert-de-montserrat** [comment]
Rather than modifying `compute_τij`, once you know the stress tensor/invariant after running `compute_τij`, you could add a function similar to [compute_εII](https://github.com/JuliaGeodynamics/GeoParams.jl/blob/05ca03d12cbc03c200ae6abd64f368dce7201637/src/CompositeRheologies/CompositeRheology.jl#L80) but using `ntuple` instead of `nreduce`, that should give you a tuple with the strain rate componentes of your composite:
```julia
compute_elements_εII(v::CompositeRheology{T,N}, τII, args) where {T, N} = ntuple(i -> first(compute_εII( v.elements[i], τII, args)), Val(N))
```

**Comment by ArneSpang** [comment]
Thank you for the quick response! I will try this out

**Comment by boriskaus** [comment]
can this be closed?

**Comment by ArneSpang** [comment]
Yeah, the function was included around the last hackathon
